server {
    listen 80;
    server_name paaas.siriusdevops.com;

    root /usr/share/nginx/html;

    location / {
        try_files /paaas-landing.html =404;
    }
}

server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files /index.html =404;
    }
}
